source 'http://rubygems.org'

gem "capybara", "3.35.3"
gem "cucumber", "7.0.0"
gem 'hoe', '~> 3.23'
gem 'hoe-bundler', '~> 1.5'
gem 'hoe-deveiate', '~> 0.10.0'
gem 'hoe-highline', '~> 0.2.1'
gem 'hoe-mercurial', '~> 1.4', '>= 1.4.1'
gem 'rake-compiler', '~> 1.1', '>= 1.1.1'
gem 'rake-compiler-dock', '~> 1.1'
gem 'rdoc', '~> 6.0'
gem "rspec", "3.10.0"
gem "selenium-webdriver", "3.142.7"

